In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
df = pd.read_csv("training-set.csv")
df.head()

ID     Sex Bachelor   Age Graduated            Career  \
0  1462220581    Male       No  41.0       Yes  Fashion Designer   
1  1462220232  Female      Yes  38.0       Yes                HR   
2  1462226544    Male      Yes  41.0       Yes  Fashion Designer   
3  1462224171    Male       No  21.0        No            Doctor   
4  1462226427  Female       No  37.0       Yes  Fashion Designer   

   Work Experience Family Expenses Family  Size Variable Segmentation  \
0              2.0             Low            3    Dog_6       Akshat   
1              0.0         Average            2    Dog_6       Akshat   
2              0.0            High            5    Dog_6      Bhavesh   
3              0.0             Low            4    Dog_6        Darsh   
4              0.0             Low            1    Dog_2      Bhavesh   

                                    Description  
0     The specimen is reliable and experienced.  
1     The specimen is reliable and experienced.  
2     The specimen is reliable and experienced.  
3  The specimen is responsible and hardworking.  
4     The specimen is reliable and experienced.

In [2]:
from sklearn.model_selection import train_test_split

In [2]:
x = df.drop("Segmentation",axis = 1)
x = df.drop("ID",axis = 1)
y = df["Segmentation"]
#y = df["ID"]

In [3]:
#Filling the missing values using the scikit learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#filling the categorical values with missing and numerical values with mean
cat_imputer =SimpleImputer(strategy="constant",fill_value="missing")
#door_imputer = SimpleImputer(strategy="constant",fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

#defining columns
cat_features = ["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable"]

num_features=["Age","Work Experience"]

#Creating an imputer (something that fills the data)
imputer = ColumnTransformer([
    ("cat_imputer" ,cat_imputer,cat_features),
    
    ("num_imputer",num_imputer,num_features)  ])

#Fill train and test data separately
filled_X = imputer.fit_transform(x)
#filled_X_test = imputer.transform(x_test)

#check filled x_train
filled_X


array([['Male', 'No', 'Yes', ..., 'Dog_6', 41.0, 2.0],
       ['Female', 'Yes', 'Yes', ..., 'Dog_6', 38.0, 0.0],
       ['Male', 'Yes', 'Yes', ..., 'Dog_6', 41.0, 0.0],
       ...,
       ['Male', 'Yes', 'Yes', ..., 'Dog_6', 42.0, 9.0],
       ['Female', 'Yes', 'Yes', ..., 'Dog_6', 27.0, 2.646629877808435],
       ['Female', 'Yes', 'Yes', ..., 'Dog_6', 56.0, 0.0]], dtype=object)

In [4]:
df_filled_train = pd.DataFrame(filled_X,
                                      columns=["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable","Age","Work Experience"])

#df_filled_test = pd.DataFrame(filled_X_test,
                                     #columns=["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable","Age","Work Experience"])
df_filled_train.isna().sum()

Sex                0
Bachelor           0
Graduated          0
Career             0
Family Expenses    0
Family  Size       0
Variable           0
Age                0
Work Experience    0
dtype: int64

In [5]:
from sklearn.preprocessing import OneHotEncoder
categorical_features=["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")

#fill train and test values separately
transformed_X_train= transformer.fit_transform(df_filled_train)
#transformed_X_test = transformer.transform(df_filled_test)

#checkig transformed and filled values
transformed_X_train.toarray()

array([[ 0.        ,  1.        ,  0.        , ...,  0.        ,
        41.        ,  2.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
        38.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
        41.        ,  0.        ],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
        42.        ,  9.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
        27.        ,  2.64662988],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
        56.        ,  0.        ]])

In [6]:
from sklearn.preprocessing import OneHotEncoder

# Example y_train and y_test data

# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder on y_train and transform both y_train and y_test
transformed_y = encoder.fit_transform([[label] for label in y])
#transformed_y_test = encoder.transform([[label] for label in y_test])

print("Encoded y_train:")
print(transformed_y)

#print("Encoded y_test:")
#print(transformed_y_test)


Encoded y_train:
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [55]:
#fitting the data into the model
np.random.seed(42)
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=1000)
#fitting the hot encoded data
clf.fit(transformed_X_train,transformed_y)

RandomForestClassifier(n_estimators=1000)

In [56]:
clf.score(transformed_X_train,transformed_y)

0.9608641756684966

In [7]:
fd = pd.read_csv("testting-set.csv")

In [8]:
fd.drop("ID",axis = 1)

Sex Bachelor   Age Graduated            Career  Work Experience  \
0     Female      Yes  42.0        No         Scientist              4.0   
1     Female       No  41.0       Yes  Fashion Designer              0.0   
2     Female       No  18.0        No            Doctor              2.0   
3       Male       No  30.0       Yes            Doctor              1.0   
4       Male      Yes  81.0       Yes            Lawyer              1.0   
...      ...      ...   ...       ...               ...              ...   
2416    Male       No  42.0       Yes            Singer              2.0   
2417    Male      Yes  89.0        No            Lawyer              NaN   
2418    Male       No  47.0       Yes            Singer              4.0   
2419  Female      Yes  79.0       Yes            Lawyer              0.0   
2420  Female      Yes  84.0       Yes            Lawyer              0.0   

     Family Expenses  Family  Size Variable  \
0                Low           1.0    Dog_6   
1                Low           1.0    Dog_6   
2                Low           5.0    Dog_6   
3                Low           4.0    Dog_6   
4                Low           1.0    Dog_6   
...              ...           ...      ...   
2416             Low           1.0    Dog_3   
2417             Low           2.0    Dog_6   
2418             Low           1.0    Dog_6   
2419            High           2.0    Dog_6   
2420             Low           1.0    Dog_6   

                                          Description  
0           The specimen is reliable and experienced.  
1           The specimen is reliable and experienced.  
2     The specimen is rather joyful than responsible.  
3           The specimen is reliable and experienced.  
4           The specimen is reliable and experienced.  
...                                               ...  
2416        The specimen is reliable and experienced.  
2417        The specimen is reliable and experienced.  
2418        The specimen is reliable and experienced.  
2419        The specimen is reliable and experienced.  
2420        The specimen is reliable and experienced.  

[2421 rows x 10 columns]

In [9]:
#Filling the missing values using the scikit learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#filling the categorical values with missing and numerical values with mean
cat_imputer =SimpleImputer(strategy="constant",fill_value="missing")
#door_imputer = SimpleImputer(strategy="constant",fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

#defining columns
cat_features = ["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable"]

num_features=["Age","Work Experience"]

#Creating an imputer (something that fills the data)
imputer = ColumnTransformer([
    ("cat_imputer" ,cat_imputer,cat_features),
    
    ("num_imputer",num_imputer,num_features)  ])

#Fill train and test data separately
filled_X = imputer.fit_transform(x)
#filled_X_test = imputer.transform(x_test)

#check filled x_train
filled_X


array([['Male', 'No', 'Yes', ..., 'Dog_6', 41.0, 2.0],
       ['Female', 'Yes', 'Yes', ..., 'Dog_6', 38.0, 0.0],
       ['Male', 'Yes', 'Yes', ..., 'Dog_6', 41.0, 0.0],
       ...,
       ['Male', 'Yes', 'Yes', ..., 'Dog_6', 42.0, 9.0],
       ['Female', 'Yes', 'Yes', ..., 'Dog_6', 27.0, 2.646629877808435],
       ['Female', 'Yes', 'Yes', ..., 'Dog_6', 56.0, 0.0]], dtype=object)

In [10]:
fd_filled_test = pd.DataFrame(filled_X,
                                      columns=["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable","Age","Work Experience"])

#df_filled_test = pd.DataFrame(filled_X_test,
                                     #columns=["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable","Age","Work Experience"])
fd_filled_test.isna().sum()

Sex                0
Bachelor           0
Graduated          0
Career             0
Family Expenses    0
Family  Size       0
Variable           0
Age                0
Work Experience    0
dtype: int64

In [11]:
from sklearn.preprocessing import OneHotEncoder
categorical_features=["Sex","Bachelor","Graduated","Career","Family Expenses","Family  Size","Variable"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")

#fill train and test values separately
transformed_X_test= transformer.fit_transform(fd_filled_test)
#transformed_X_test = transformer.transform(df_filled_test)

#checkig transformed and filled values
transformed_X_test.toarray()

array([[ 0.        ,  1.        ,  0.        , ...,  0.        ,
        41.        ,  2.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
        38.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
        41.        ,  0.        ],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
        42.        ,  9.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
        27.        ,  2.64662988],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
        56.        ,  0.        ]])

In [58]:
sd = pd.DataFrame(pds,columns=["Akshat"," Bhavesh", "Chaitanya", " Darsh"],
                 )
# csv_filename="resilts.csv"
# sd.to_csv(csv_filename,index=False)
# print(csv_filename)

In [75]:
# Transform rows to keep only column names where the value is 1
sd_customized = sd.apply(lambda row: [col for col, val in row.items() if val == 1], axis=1)

# Combine the result into a single row
result = pd.DataFrame({'Customized Row': [", ".join(row) for row in sd_customized if row]})

In [79]:
result['ID']=fd['ID']

In [80]:
csv_filename="submit00.csv"
result.to_csv(csv_filename,index=False)
print(csv_filename)

submit00.csv


In [81]:
result.head()

Customized Row            ID
0         Akshat  1.462225e+09
1         Akshat  1.462220e+09
2        Bhavesh  1.462226e+09
3          Darsh  1.462224e+09
4        Bhavesh  1.462223e+09

In [62]:
sd.ndim

2

In [12]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(transformed_X_train,transformed_y)
y_pred_knn = knn.predict(transformed_X_test)

In [15]:
kn = pd.DataFrame(y_pred_knn,columns=["Akshat"," Bhavesh", "Chaitanya", " Darsh"],
                 )

In [38]:
# Transform rows to keep only column names where the value is 1
kn_customized = kn.apply(lambda row: [col for col, val in row.items() if val == 1], axis=1)

# Combine the result into a single row
result_knn = pd.DataFrame({'Customized Row': [", ".join(row) for row in kn_customized if row]})

In [39]:
result_knn['ID']=fd['ID']

In [40]:
result_knn.tail

<bound method NDFrame.tail of      Customized Row            ID
0            Akshat  1.462225e+09
1           Bhavesh  1.462220e+09
2             Darsh  1.462226e+09
3           Bhavesh  1.462224e+09
4            Akshat  1.462223e+09
...             ...           ...
4499         Akshat           NaN
4500        Bhavesh           NaN
4501         Akshat           NaN
4502          Darsh           NaN
4503        Bhavesh           NaN

[4504 rows x 2 columns]>

In [41]:
result_knn['ID'] = result_knn['ID'].replace('', np.nan)

In [46]:
# Drop rows where either 'id' or 'customise' has NaN
result_knn = result_knn.dropna(subset=['ID', 'Customized Row'])


AttributeError: 'NoneType' object has no attribute 'dropna'

In [45]:
result_knn.dtypes

AttributeError: 'NoneType' object has no attribute 'dtypes'

In [35]:
csv_filename="submit_knn_dropped.csv"
result_knn.to_csv(csv_filename,index=False)
print(csv_filename)

AttributeError: 'NoneType' object has no attribute 'to_csv'

In [27]:
result_knn.head()

Customized Row            ID
0         Akshat  1.462225e+09
1        Bhavesh  1.462220e+09
2          Darsh  1.462226e+09
3        Bhavesh  1.462224e+09
4         Akshat  1.462223e+09