In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


In [6]:
a1= np.array([1,2,34])

a2 = np.array([[1,2,3,4],
               [23,4,52,234]])

In [7]:
a1

array([ 1,  2, 34])

In [8]:
a2

array([[  1,   2,   3,   4],
       [ 23,   4,  52, 234]])

In [9]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 4), 2, dtype('int32'), 8, numpy.ndarray)

## Arrays

In [10]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [12]:
#this gives new array of given shape and type filled with ones with data type as float
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#Return a new array of given shape and type, filled with zeros.
zeroes = np.zeros((2,4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
#Return evenly spaced values within a given interval. we need to specify the start,stop and step over values
rangeOfArray = np.arange(0,6,2)
rangeOfArray

array([0, 2, 4])

In [17]:
#Return random integers from `low` (inclusive) to `high` (exclusive).
random_array = np.random.randint(0,10,size = (2,3))
random_array

array([[0, 9, 0],
       [9, 4, 2]])

In [18]:
random_array.shape

(2, 3)

In [19]:
random_array.size

6

In [20]:
#Return random floats in the half-open interval [0.0, 1.0)
random_array_2 = np.random.random((3,4))
random_array_2

array([[0.06057067, 0.98075099, 0.77080225, 0.88528919],
       [0.32378477, 0.65312967, 0.42851342, 0.31718671],
       [0.26508592, 0.66598365, 0.71214448, 0.75686972]])

## Pseudo random numbers or random.seed()

In [21]:
np.random.seed(6)
random_array_3 = np.random.random((4,3))
random_array_3

array([[0.89286015, 0.33197981, 0.82122912],
       [0.04169663, 0.10765668, 0.59505206],
       [0.52981736, 0.41880743, 0.33540785],
       [0.62251943, 0.43814143, 0.73588211]])

## View of arrays and matrices

In [22]:
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [23]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [24]:
a2[1]

array([ 23,   4,  52, 234])

In [25]:
a2.shape

(2, 4)

In [27]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[2, 0, 0, 5, 0],
         [0, 8, 1, 0, 9],
         [7, 1, 8, 9, 5],
         [8, 3, 4, 2, 1]],

        [[5, 5, 8, 3, 4],
         [6, 9, 6, 9, 4],
         [6, 5, 5, 8, 8],
         [7, 4, 0, 9, 2]],

        [[0, 7, 2, 8, 1],
         [2, 9, 4, 4, 4],
         [3, 3, 4, 1, 0],
         [1, 3, 0, 5, 8]]],


       [[[7, 7, 5, 4, 6],
         [8, 7, 6, 4, 7],
         [4, 4, 4, 2, 5],
         [7, 2, 2, 0, 8]],

        [[1, 5, 5, 5, 6],
         [9, 0, 7, 7, 6],
         [2, 5, 0, 9, 1],
         [0, 6, 9, 9, 3]],

        [[2, 3, 2, 4, 0],
         [6, 0, 2, 0, 6],
         [9, 5, 4, 1, 7],
         [5, 7, 8, 2, 7]]]])

In [29]:
a5 = a4[:, :, :, :4]
a5

array([[[[2, 0, 0, 5],
         [0, 8, 1, 0],
         [7, 1, 8, 9],
         [8, 3, 4, 2]],

        [[5, 5, 8, 3],
         [6, 9, 6, 9],
         [6, 5, 5, 8],
         [7, 4, 0, 9]],

        [[0, 7, 2, 8],
         [2, 9, 4, 4],
         [3, 3, 4, 1],
         [1, 3, 0, 5]]],


       [[[7, 7, 5, 4],
         [8, 7, 6, 4],
         [4, 4, 4, 2],
         [7, 2, 2, 0]],

        [[1, 5, 5, 5],
         [9, 0, 7, 7],
         [2, 5, 0, 9],
         [0, 6, 9, 9]],

        [[2, 3, 2, 4],
         [6, 0, 2, 0],
         [9, 5, 4, 1],
         [5, 7, 8, 2]]]])

## Manipulating arrays

In [31]:
a1 +ones

array([[ 2.,  3., 35.],
       [ 2.,  3., 35.]])

In [32]:
a1 - ones

array([[ 0.,  1., 33.],
       [ 0.,  1., 33.]])

In [33]:
a2

array([[  1,   2,   3,   4],
       [ 23,   4,  52, 234]])

In [36]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

In [37]:
a1*a2

array([[  1. ,   4. , 112.2],
       [  4. ,  10. , 221. ]])

In [38]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [39]:
np.add(a1,ones)

array([[ 2.,  3., 35.],
       [ 2.,  3., 35.]])

In [40]:
np.exp(a1)

array([2.71828183e+00, 7.38905610e+00, 5.83461743e+14])

In [41]:
np.log(a1)

array([0.        , 0.69314718, 3.52636052])

## Aggregation

There are some functions that are available in python as well as in numpy but we must use python functions for python dtypes and numpy functions for numpy dtype

In [42]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
np.mean(a2)

3.6333333333333333

In [44]:
#it gives the measure of how a group of numbr is different from its mean.
np.std(a2)

1.8226964152656422

In [45]:
#variance gives the idea of avg degree to whs each number is different from mean
# higher varaince means wider range and vice versa
np.var(a2)

3.3222222222222224

In [46]:
np.max(a2)

6.5

In [47]:
np.min(a2)

1.0

In [48]:
import matplotlib.pyplot as plt

### Reshape and transpose

In [49]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [51]:
a3 = np.array ([[[ 1,2,3],
                 [4,5,6],
                [7,8,9]],

               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [52]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [53]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [54]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [55]:
#transpose switches the axis of a matrix
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [56]:
a3.T.shape

(3, 3, 2)

### Dot Product

In [58]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [59]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [60]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [61]:
mat2.shape

(5, 3)

In [64]:
mat1.shape , mat2.T.shape

((5, 3), (3, 5))

In [66]:
mat3 = np.dot(mat1,mat2.T)

In [67]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [68]:
mat3.shape

(5, 5)

### Creating a personalised data set

In [113]:
np.random.seed(0)
sales = np.random.randint(10,size = (5,3))
sales

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [70]:
import pandas as pd

In [114]:
week_sales = pd.DataFrame(sales ,
                          index = ["Mon","Tue","Wed","Thurs","Fri"],
                          columns  = ["Mango","Apple","Others"])
week_sales

Mango  Apple  Others
Mon        5      0       3
Tue        3      7       9
Wed        3      5       2
Thurs      4      7       6
Fri        8      8       1

In [100]:
price = np.array([100,99,97])
prices = pd.DataFrame(price.reshape(1,3),
                      index = ["Price"],
                      columns = ["Mango","Apple","Others"])
prices

Mango  Apple  Others
Price    100     99      97

In [110]:
sales.shape

(5, 2)

In [111]:
price.shape

(3,)

In [115]:
total = price.dot(sales.T)
total

array([ 791, 1866,  989, 1675, 1689])

In [116]:
prices.shape , week_sales.shape

((1, 3), (5, 3))

In [117]:
daily_sales = prices.dot(week_sales.T)
daily_sales

Mon   Tue  Wed  Thurs   Fri
Price  791  1866  989   1675  1689

In [121]:
week_sales["Total (INR)" ]= daily_sales.T
week_sales

Mango  Apple  Others  Total (INR)
Mon        5      0       3          791
Tue        3      7       9         1866
Wed        3      5       2          989
Thurs      4      7       6         1675
Fri        8      8       1         1689

### above dataset is created by proper matrix multiplication 

In [122]:
a1

array([ 1,  2, 34])

In [123]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [124]:
a1 > a2

array([[False, False,  True],
       [False, False,  True]])

### Sorting arrays

In [125]:
random_array

array([[0, 9, 0],
       [9, 4, 2]])

In [126]:
np.sort(random_array)

array([[0, 0, 9],
       [2, 4, 9]])

In [127]:
np.argsort(random_array)

array([[0, 2, 1],
       [2, 1, 0]], dtype=int64)

In [128]:
np.argmax(random_array , axis =0)

array([1, 0, 1], dtype=int64)

### An example of how to use NumPy

<img src= "images/panda.png"/>

### Converting an images into numbers

In [137]:
from matplotlib.image import imread

panda = imread("images/panda.png")

In [138]:
panda.size ,panda.shape

(24465000, (2330, 3500, 3))

In [139]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0